# Force gcc 11 to avoid a problem with CUDA 12, GCC 12 and pybind11
# xref: https://github.com/pybind/pybind11/issues/4606
c_compiler_version:            # [linux]
  - 11                         # [linux]
cxx_compiler_version:          # [linux]
  - 11                         # [linux]
